version: '3.9'
name: 'ip-spoofing-detector'

services:
  packet-generator-backend:
    image: gabolemus/packet-generator
    container_name: packet-generator-backend
    ports:
      - 8080:8080

  packet-generator-frontend:
    image: gabolemus/packet-generator-frontend
    container_name: packet-generator-frontend
    ports:
      - 80:80
    depends_on:
      - packet-generator-backend

  tcpdump:
    image: gabolemus/packet-monitor
    container_name: traffic-capture
    network_mode: "host"
    volumes:
      - ./Network-Analysis/tcpdump:/tcpdump
    command: -i any -w /tcpdump/network-traffic.pcap
    depends_on:
      - packet-generator-backend

  traffic-analyzer:
    image: gabolemus/packet-parser
    container_name: packet-parser
    volumes:
      - ./Network-Analysis/tcpdump:/tcpdump
      - ./Network-Analysis/traffic-analysis:/traffic-analysis
    depends_on:
      - packet-generator-backend
      - tcpdump
    command:
      - ./tcpdump/network-traffic.pcap
      - -o
      - /traffic-analysis/
      - -t
      - '5'
