version: '3.9'
name: 'ip-spoofing-detector'

services:
  packet-generator:
    image: gabolemus/packet-generator
    container_name: packet-generator
    ports:
      - 8080:8080

  tcpdump:
    image: gabolemus/packet-monitor
    container_name: traffic-capture
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
    command: -i any -w /tcpdump/network-traffic.pcap
    depends_on:
      - packet-generator

  traffic-analyzer:
    # image: gabolemus/traffic-analyzer
    build:
      context: ./Traffic-Monitor
      dockerfile: Dockerfile
    container_name: traffic-analyzer
    volumes:
      - ./tcpdump:/tcpdump
      - ./traffic-analysis:/traffic-analysis
    depends_on:
      - packet-generator
      - tcpdump
    command:
      - ./tcpdump/network-traffic.pcap
