name: Production Environment Deployment

on:
  push:
    branches:
      - main

jobs:
  traffic-generator-image:
    name: Publish latest Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build TCP/IP Traffic Generator image
        run: |
          cd Packet-Generator/server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/packet-generator:latest .
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/packet-generator:latest

  traffic-monitor-image:
    name: Publish latest Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build TCP/IP Traffic Monitor image
        run: |
          cd Traffic-Monitor/TCP-Dump
          docker build -t ${{ secrets.DOCKER_USERNAME }}/packet-monitor:latest .
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/packet-monitor:latest
