name: Production Environment Deployment

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Publish latest Docker image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build TCP/IP Traffic Generator image
        run: |
          cd Packet-Generator/server
          docker build -t $REPO/packet-generator:latest -t $REPO/packet-generator:$IMAGE_TAG .
      - name: Push image to DockerHub
        run: docker push $REPO
