name: Production Environment Deployment

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Publish latest Docker image
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build TCP/IP Traffic Generator image
        run: |
          cd Packet-Generator/server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/packet-generator:latest -t ${{ secrets.DOCKER_USERNAME }}/packet-generator:${{ github.sha }} .
      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/packet-generator:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/packet-generator:${{ github.sha }}
