name: Production Environment Deployment

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Publish latest Docker image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Change working directory
        run: cd Packet-Generator/server/
      - name: Build TCP/IP Traffic Generator image
        run: docker build -t $REPO:latest -t $REPO:${{ github.sha }} .
      - name: Push image to DockerHub
        run: docker push $REPO
